### ISSUE TITLE
Dashboard SQL - Pending Posts

### ISSUE THREAD

**Issue by jp-ong** [iflexhibit/iflexhibit-api#132]
### Dashboard SQL - Pending Posts

Base: `main`
New branch: `sql-132-pending-posts`

---

**Prerequisites**:

- [x] Finish reading the entire issue before beninging.

---

**Requirements**:

- Create a file called `pending_posts.sql` in the `sql/_dashboard` folder
- Create an SQL command the would fetch the following fields:
  - ID of the post
  - user id of the post creator
  - username of the post creator
  - post title
  - post body
  - post image
  - post video
  - date of post creation
- Sort the posts by their date of creation from earliest to most recent
- You may use create view if you wish

**Design**
![image](https://user-images.githubusercontent.com/64911824/152151429-c488aecf-2a57-4ca2-a583-164b3b40911f.png)
![image](https://user-images.githubusercontent.com/64911824/152151510-008e78e1-68cc-4280-97a0-78a4a8ad249d.png)

---

**Notes**:

- none

**Comment by jp-ong** [comment]
@LyndonTomas Added design screenshots as reference

**Comment by gilkarol** [comment]
Hi, can i do it?
