### ISSUE TITLE
Add sql command to update user profile

### ISSUE THREAD

**Issue by LyndonTomas** [iflexhibit/iflexhibit-api#58]
### Add sql command to update user profile

Base: `main`
New branch: `sql-58-update-profile`

---

**Prerequisites**:

- none

---

**Requirements**:

- Filename: `update_profile.sql`
- Query must update the following fields of the user that matches the `user_id`:
  - username
  - contact
  - bio
- Make sure to also update `updated_at` to current date
- Return `user_id`

**Comment by jp-ong** [comment]
Updated requirements:
- Removed `avatar_image` and `background_image`

@LyndonTomas
