### ISSUE TITLE
Enhance the fetch posts sql query

### ISSUE THREAD

**Issue by jp-ong** [iflexhibit/iflexhibit-api#94]
### Enhance the fetch posts sql query

Base: `main`
New branch: `sql-94-enhance-fetch-posts`

---

**Prerequisites**:

- none

---

**Requirements**:

- Files affected:
  - `fetch_all_guest.sql`: Pagination, Sorting, Filtering, Searching
  - `fetch_user_posts.sql`: Pagination, Sorting
- **Pagination**
  - Maximum posts to be displayed would be 15
  - The query must know what the user's current page is.
  - i.e. if the user is on page 2, the query must output posts 16-30 instead of 1-15, 31-45, or 11-25
- **Sorting**
  - Most Viewed
  - Most Liked
  - Most Discussed (# of comments)
  - Most Recent
  - _Add more sorting options if you wish_
- **Filtering** by tags
  - Use [**Pattern Matching**](https://www.postgresql.org/docs/9.3/functions-matching.html)
  - The server will supply the pattern.
  - Sample pattern: `%Photography%Portrait%Traditional%`
    - This pattern implies that posts that have **at least** the above tags Photography, Portrait, and Traditional must appear, even if the post includes other tags.
    - If the post only had Photography and Portrait, it would not be included.
    - `2d Art,Photography,Portrait,Sculpture,Traditional` ✔️ match
    - `2d Art,Photography,Portrait,Sculpture` ❌ mismatch
- **Searching** by title
  - Use [**Pattern Matching**](https://www.postgresql.org/docs/9.3/functions-matching.html)
  - Sample pattern: `%Post Title%`

---

**Notes**:

- Include a documentation of the variables in both files. Sample:
```sql
-- $1 - user's current page
-- $2 - user's selected sorting option
```
- Commit Pagination, Sorting, Searching, and Filtering **separately**.
- Provide screenshots that demonstrates each of the three **separately**.

**Comment by LyndonTomas** [comment]
technically, we already did most recent since the code was arranging it by `ORDER BY posts.created_at DESC`

**Comment by jp-ong** [comment]
Issue reopened.
- Use the existing branch `sql-94-enhance-fetch-posts`.
- Update these two files with the new command.
  - `fetch_all_guest.sql`: Pagination, Sorting, Filtering, Searching
  - `fetch_user_posts.sql`: Pagination, Sorting
- Updates:
  - New pattern matching syntax for title.
  - New ORDER BY implementation
  - Include updated_at as returned field
  - Change default field to sort by from `post_id` to `updated_at`
  - Remove tag-filtering and title-searching related commands from `fetch_user_posts.sql`
